export const SUPPORTED_STYLES = [
    'background',
    'background-color',
    'border',
    'border-bottom',
    'border-bottom-color',
    'border-bottom-style',
    'border-bottom-width',
    'border-color',
    'border-left',
    'border-left-color',
    'border-left-style',
    'border-left-width',
    'border-right',
    'border-right-color',
    'border-right-style',
    'border-right-width',
    'border-style',
    'border-top',
    'border-top-color',
    'border-width',
    'font-variant',
    'font-weight',
    'height',
    'letter-spacing',
    'line-height',
    'padding',
    'padding-bottom',
    'padding-left',
    'padding-right',
    'padding-top',
    'table-layout',
    'text-indent',
    'text-transform',

]


